version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
  - id: supervisord
    env:
      - CGO_ENABLED=0
    main: ./cmd/supervisord
    binary: supervisord
    ldflags:
      - -X main.BuildVersion={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
  - id: pidproxy
    env:
      - CGO_ENABLED=0
    main: ./cmd/pidproxy
    binary: pidproxy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: [ "binary" ]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# brews:
#   - homepage: 'https://github.com/sgaunet/supervisord'
#     description: 'A simple and efficient Markdown to HTML converter'
#     directory: Formula
#     commit_author:
#       name: sgaunet
#       email: 1552102+sgaunet@users.noreply.github.com
#     repository:
#       owner: sgaunet
#       name: homebrew-tools
#       # Token with 'repo' scope is required for pushing to a different repository
#       token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
#     url_template: 'https://github.com/sgaunet/supervisord/releases/download/{{ .Tag }}/{{ .ArtifactName }}'
#     install: |
#       bin.install "{{ .ArtifactName }}" => "supervisord"
#     test: |
#       system "#{bin}/supervisord", "-h"